title: Brendan Burns # your name (or website title) here
logo: "/images/logo2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analyst at <a href="https://data.safeworkaustralia.gov.au">Safe Work Australia</a>.
  <br><br>
  Data Analyst with 1.5 years of public service experience in analytics, ETL and visualisation.
  <br><br>
  Bachelors degree in Science(Applied Mathematics) from Swinburne University,
  Graduate certificate in Data Science from UNSW.
  <br><br>
  <a href="https://www.linkedin.com/in/brendan-burns-a7527223a/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal

google_analytics: <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7QG66FJZDT"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7QG66FJZDT');
</script>
